# Numpy - Part 2

In [1]:
import numpy as np

### 4. Operation

In [2]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
a.sum()

78

In [4]:
a.sum(axis=0)       # 행

array([15, 18, 21, 24])

In [5]:
a.sum(axis=1)       # 열

array([10, 26, 42])

In [6]:
np.sum(a[0])        # 첫번째 행

10

- sorting

In [8]:
b = np.array([[4,3,5,7],[1,12,11,9],[2,5,1,14]])
b

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2,  5,  1, 14]])

In [9]:
np.sort(b)      # axis=1, ascending order  # 결과값만 정렬해줌

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [10]:
b.sort()        # b 변수 자체가 바뀜

In [11]:
b

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [12]:
np.sort(b, axis=0)

array([[ 1,  2,  5,  7],
       [ 1,  4,  5, 12],
       [ 3,  9, 11, 14]])

In [13]:
# 내림차순일 경우에는 아래와 같은 방법으로
c = np.array([42, 38, 12, 25])
np.sort(c)[::-1]

array([42, 38, 25, 12])

In [14]:
np.argsort(c)       # 인덱스 값으로 나타냄

array([2, 3, 1, 0], dtype=int64)

In [16]:
indices = np.argsort(c)
c[indices]

array([12, 25, 38, 42])

In [17]:
c[[2,3,1,0]]

array([12, 25, 38, 42])

- Mathematical Functions

In [18]:
def sigmoid(x):
    return 1. / (1 + np.exp(-x))

In [19]:
xs = np.array([-10,0,10])
sigmoid(xs)

array([4.53978687e-05, 5.00000000e-01, 9.99954602e-01])

- Transpose(전치행렬)

In [20]:
b

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [21]:
b.T

array([[ 3,  1,  1],
       [ 4,  9,  2],
       [ 5, 11,  5],
       [ 7, 12, 14]])

- concatenate, vstack, hstack

In [22]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [24]:
b = b = np.array([[5, 6]])
b

array([[5, 6]])

In [25]:
np.vstack((a, b))       # vertical stack

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
np.hstack((a, b.T))     # horizontal stack

array([[1, 2, 5],
       [3, 4, 6]])

- Array Operation

In [27]:
a + a

array([[2, 4],
       [6, 8]])

In [28]:
a - a

array([[0, 0],
       [0, 0]])

In [29]:
a * a

array([[ 1,  4],
       [ 9, 16]])

In [30]:
a / a

array([[1., 1.],
       [1., 1.]])

- Broadcasting

In [31]:
a + 3

array([[4, 5],
       [6, 7]])

- Dot Product

In [32]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(1,13).reshape(3,4)

In [33]:
np.dot(a,b)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128]])

In [34]:
a.dot(b)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128]])

### 5. Comparison

- All & Any

In [35]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [37]:
np.any(a>5), np.all(a>5)        # any => or, all => and

(True, False)

- Logical Operation

In [39]:
b = np.logical_and(a > 3, a < 7)
b

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [40]:
np.logical_or(a < 3, a > 7)

array([ True,  True,  True, False, False, False, False, False,  True,
        True])

- argmax, argmin

In [41]:
np.argmax(a), np.argmin(a)

(9, 0)

### 6. Boolean & Fancy Index

In [45]:
a[a > 5]

array([6, 7, 8, 9])

In [43]:
b

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [42]:
a[b]

array([4, 5, 6])

In [44]:
a[np.logical_or(a < 3, a > 7)]

array([0, 1, 2, 8, 9])

In [47]:
a[[3,5,7,3]]        # 중복값도 가능

array([3, 5, 7, 3])

### 7. 기술 통계

In [48]:
a = np.random.randn(10)
a

array([ 1.09362484, -1.28392145,  0.82676047,  0.91593404, -0.11347917,
       -0.83886691, -0.29734282, -0.81444284,  0.60737371,  0.55547283])

In [49]:
# 평균(Mean)
a.mean(), np.mean(a)

(0.06511126990292525, 0.06511126990292525)

In [50]:
# 표준 편차(Standard Deviation)
a.std(),np.std(a)

(0.8043818043128216, 0.8043818043128216)

In [51]:
a.max(), a.min()

(1.0936248393604073, -1.2839214542374535)

In [52]:
# 4분위수
np.percentile(a, 0)

-1.2839214542374535

In [54]:
np.percentile(a, 100), np.percentile(a, 0)

(1.0936248393604073, -1.2839214542374535)

In [53]:
np.percentile(a, 25), np.percentile(a, 75)

(-0.6851678386335986, 0.7719137822834813)

In [56]:
np.percentile(a, 50), np.median(a)

(0.22099683289005118, 0.2209968328900512)