In [2]:
import numpy as np

### 1.

In [3]:
np.arange(1,9).reshape(2,4)*10

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

### 2.

slice가 두 개면 2차원, 한 개면 1차원, 없으면 값

In [6]:
m = np.arange(15).reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
m[(1,2)], m[-1,-1]

(7, 14)

In [8]:
m[1,1:3]

array([6, 7])

### 3.

In [15]:
f = np.array(m).flatten()
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
f[f % 3 == 0]

array([ 0,  3,  6,  9, 12])

In [21]:
f[f % 4 == 1]

array([ 1,  5,  9, 13])

In [55]:
f1 = np.logical_and(f % 3 == 0, f % 4 == 1)
f[f1]

array([9])

In [54]:
f1 = np.logical_and(f % 3 == 0, f % 4 == 1)
f1

array([ True])

In [52]:
b = np.arange(4)
b

array([0, 1, 2, 3])

In [65]:
b = np.eye(N=5,M=5,k=1)
b1 =  np.eye(N=5,M=5,k=0)
b2 = np.eye(N=5,M=5,k=-1)
b + b1 * 2 + b2 * 3

array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

In [3]:
random_num = 10 * np.random.random_sample((5, 6)) + 0
random_num

array([[3.64133319, 7.21665923, 6.44667269, 5.1507481 , 6.73148046,
        5.24386846],
       [9.55310742, 9.7277522 , 8.36537123, 3.58898273, 1.79559557,
        2.17626493],
       [3.07140738, 8.47863469, 8.15797795, 1.51018741, 2.03412389,
        2.29277026],
       [6.89533689, 1.74048541, 8.16122821, 5.30429483, 9.60212376,
        4.49291677],
       [9.36068859, 7.26363486, 3.74895758, 5.32979516, 8.49312557,
        1.27379936]])

In [4]:
np.max(random_num)

9.727752201022318

In [5]:
random_num.sum(axis=1)

array([34.43076212, 35.20707408, 25.54510157, 36.19638587, 35.47000113])

In [6]:
np.argmax(random_num, axis=1)

array([1, 1, 1, 4, 0], dtype=int64)

In [22]:
random_num.max(axis=1)

array([7.21665923, 9.7277522 , 8.47863469, 9.60212376, 9.36068859])

In [7]:
np.mean(random_num, axis=0)

array([6.50437469, 6.88543328, 6.97604153, 4.17680165, 5.73128985,
       3.09592396])

In [8]:
np.argmin(random_num, axis=0)

array([2, 3, 4, 2, 1, 4], dtype=int64)

In [23]:
grade = np.array([[1,2,3,4],[46,99,100,71],[81,59,90,100]])
grade

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [25]:
grade1 = grade[:,grade[1].argsort()]
grade1

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [27]:
import random
i = 0
for i in range(101):
    i = random.randint(1, 6)

dice = np.array(i)
np.mean(dice)

1.0

### 8.

In [3]:
# 5개 먼저 테스트
np.random.seed(2021)
rate = np.random.normal(0, 0.01, 5)
price = 10000
for i in range(5):
    price = np.round(price * (1 + rate[i]))
    print(int(price), end=' ')

10149 10218 10175 10093 10149 

In [4]:
# 250개(list 활용)
np.random.seed(2021)
rate = np.random.normal(0, 0.01, 250)
price = 10000
price_list = []
for i in range(250):
    price = price + np.round(price*rate[i])
    price_list.append(price)

price_array = np.array(price_list, dtype=np.int32)
price_array[-10:]

array([12072, 12210, 12255, 12359, 12292, 12262, 12136, 12010, 11984,
       12113])

In [5]:
# 250개(array 활용)
np.random.seed(2021)
rate = np.random.normal(0, 0.01, 250)
price = 10000
price_array = np.empty(250, dtype=np.int32)

for i in range(250):
    price = price + np.round(price*rate[i])
    price_array[i] = price

price_array[-10:]

array([12072, 12210, 12255, 12359, 12292, 12262, 12136, 12010, 11984,
       12113])

array는 값이 변할 수 있지만 사이즈가 늘어나지 않음.
따라서 empty로 비운 후 채우기
array의 단점을 보완한 것이 list